# Generated by Django 6.0 on 2025-12-23 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id_annee', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_limite_depot_cle', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id_chambre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numero_chambre', models.IntegerField()),
                ('type_chambre', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('DOUBLE', 'DOUBLE')], max_length=10)),
                ('etat_chambre', models.CharField(max_length=50)),
                ('etat_service', models.CharField(choices=[('EN_SERVICE', 'EN_SERVICE'), ('HORS_SERVICE', 'HORS_SERVICE'), ('EN_REPARATION', 'EN_REPARATION')], default='EN_SERVICE', max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('mat_etudiant', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('nationalite', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ecole', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=50)),
                ('niveau_etudes', models.CharField(choices=[('PREPA1', 'PREPA1'), ('PREPA2', 'PREPA2'), ('TS1', 'TS1'), ('TS2', 'TS2'), ('TS3', 'TS3'), ('ING1', 'ING1'), ('ING2', 'ING2'), ('ING3', 'ING3'), ('MASTER1', 'MASTER1'), ('MASTER2', 'MASTER2')], max_length=20)),
                ('est_handicape', models.BooleanField(default=False)),
                ('est_international', models.BooleanField(default=False)),
                ('etat_etudiant', models.CharField(choices=[('ACTIF', 'ACTIF'), ('SUSPENDU', 'SUSPENDU'), ('BLOQUE', 'BLOQUE')], default='ACTIF', max_length=15)),
                ('date_suspension', models.DateField(blank=True, null=True)),
                ('date_deblocage', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('GESTIONNAIRE', 'GESTIONNAIRE')], max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id_batiment', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nom_batiment', models.CharField(max_length=50)),
                ('type_public', models.CharField(choices=[('GARCONS', 'GARCONS'), ('FILLES', 'FILLES'), ('MIXTE', 'MIXTE')], max_length=10)),
                ('niveaux_etudes', models.CharField(max_length=100)),
                ('type_chambre', models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('DOUBLE', 'DOUBLE')], max_length=10)),
                ('nombre_niveaux', models.IntegerField()),
                ('nombre_chambres', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('gestionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hebergement.gestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('annee_academique', models.CharField(max_length=10)),
                ('cle_deposee', models.BooleanField(default=False)),
                ('date_depot_cle', models.DateField(blank=True, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='hebergement.chambre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='hebergement.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id_palier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('niveau_palier', models.IntegerField()),
                ('nbre_chambres', models.IntegerField(default=32)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='hebergement.batiment')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='palier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hebergement.palier'),
        ),
    ]
