-- 01_create_tables.sql

CREATE TABLE GESTIONNAIRE (
    id_gestionnaire NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(50) NOT NULL,
    prenom VARCHAR2(50) NOT NULL,
    contact VARCHAR2(20),
    email VARCHAR2(100) UNIQUE NOT NULL,
    mot_de_passe VARCHAR2(255) NOT NULL,
    role VARCHAR2(15) NOT NULL,
    date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BATIMENT (
    id_batiment VARCHAR2(1) PRIMARY KEY,
    nom_batiment VARCHAR2(50) NOT NULL,
    type_public VARCHAR2(10) NOT NULL,
    niveaux_etudes VARCHAR2(100),
    type_chambre VARCHAR2(10) NOT NULL,
    nombre_niveaux NUMBER NOT NULL,
    nombre_chambres NUMBER NOT NULL,
    capacite NUMBER NOT NULL,
    id_gestionnaire NUMBER,
    CONSTRAINT fk_bat_gest FOREIGN KEY (id_gestionnaire) REFERENCES GESTIONNAIRE(id_gestionnaire)
);

CREATE TABLE PALIER (
    id_palier VARCHAR2(10) PRIMARY KEY,
    niveau_palier NUMBER NOT NULL,
    nbre_chambres NUMBER DEFAULT 32,
    id_batiment VARCHAR2(1) NOT NULL,
    CONSTRAINT fk_pal_bat FOREIGN KEY (id_batiment) REFERENCES BATIMENT(id_batiment)
);

CREATE TABLE CHAMBRE (
    id_chambre VARCHAR2(10) PRIMARY KEY,
    numero_chambre NUMBER NOT NULL,
    type_chambre VARCHAR2(10) NOT NULL,
    etat_chambre VARCHAR2(50),
    etat_service VARCHAR2(15) DEFAULT 'EN_SERVICE',
    is_available NUMBER(1) DEFAULT 1,
    capacite NUMBER NOT NULL,
    id_palier VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_ch_pal FOREIGN KEY (id_palier) REFERENCES PALIER(id_palier)
);

CREATE TABLE ETUDIANT (
    mat_etudiant VARCHAR2(20) PRIMARY KEY,
    nom VARCHAR2(50) NOT NULL,
    prenom VARCHAR2(50) NOT NULL,
    sexe VARCHAR2(1) NOT NULL,
    nationalite VARCHAR2(50),
    telephone VARCHAR2(20),
    email VARCHAR2(100),
    ecole VARCHAR2(50),
    filiere VARCHAR2(50),
    niveau_etudes VARCHAR2(20),
    est_handicape NUMBER(1) DEFAULT 0,
    est_international NUMBER(1) DEFAULT 0,
    etat_etudiant VARCHAR2(15) DEFAULT 'ACTIF',
    date_suspension DATE,
    date_deblocage DATE
);

CREATE TABLE OCCUPATION (
    id_occupation NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mat_etudiant VARCHAR2(20) NOT NULL,
    id_chambre VARCHAR2(10) NOT NULL,
    date_entree DATE NOT NULL,
    date_sortie DATE,
    annee_academique VARCHAR2(10) NOT NULL,
    cle_deposee NUMBER(1) DEFAULT 0,
    date_depot_cle DATE,
    CONSTRAINT fk_occ_etud FOREIGN KEY (mat_etudiant) REFERENCES ETUDIANT(mat_etudiant),
    CONSTRAINT fk_occ_ch FOREIGN KEY (id_chambre) REFERENCES CHAMBRE(id_chambre)
);

CREATE TABLE ANNEE_ACADEMIQUE (
    id_annee VARCHAR2(10) PRIMARY KEY,
    libelle VARCHAR2(50) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    date_limite_depot_cle DATE NOT NULL,
    est_active NUMBER(1) DEFAULT 0
);
