-- 02_constraints.sql

ALTER TABLE GESTION_HEBERGEMENT.BATIMENT ADD CONSTRAINT chk_bat_public CHECK (type_public IN ('GARCONS', 'FILLES', 'MIXTE'));
ALTER TABLE GESTION_HEBERGEMENT.BATIMENT ADD CONSTRAINT chk_bat_ch_type CHECK (type_chambre IN ('SIMPLE', 'DOUBLE'));

ALTER TABLE GESTION_HEBERGEMENT.CHAMBRE ADD CONSTRAINT chk_ch_service CHECK (etat_service IN ('EN_SERVICE', 'HORS_SERVICE', 'EN_REPARATION'));
ALTER TABLE GESTION_HEBERGEMENT.CHAMBRE ADD CONSTRAINT chk_ch_type CHECK (type_chambre IN ('SIMPLE', 'DOUBLE'));

ALTER TABLE GESTION_HEBERGEMENT.ETUDIANT ADD CONSTRAINT chk_etud_sexe CHECK (sexe IN ('M', 'F'));
ALTER TABLE GESTION_HEBERGEMENT.ETUDIANT ADD CONSTRAINT chk_etud_etat CHECK (etat_etudiant IN ('ACTIF', 'SUSPENDU', 'BLOQUE'));

ALTER TABLE GESTION_HEBERGEMENT.GESTIONNAIRE ADD CONSTRAINT chk_gest_role CHECK (role IN ('ADMIN', 'GESTIONNAIRE'));
